In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("../Source/openskydata_raw.csv", sep=";", dtype=str)
df

,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,sensors,geo_altitude,squawk,spi,position_source
0,39de4e,TVF33SN,France,1747145538.0,1747145541,-3.6839,41.0241,10965.18,False,238.4,30.33,0.0,NaN,11049.0,6402,False,0
1,c07d0b,CGVJE,Canada,1747145541.0,1747145541,-74.3807,45.6245,297.18,False,48.42,47.15,-2.28,NaN,327.66,NaN,False,0
2,3ffc29,DMFSS,Germany,1747145490.0,1747145490,12.8925,48.2168,1219.2,False,42.19,52.43,-0.33,NaN,NaN,4453,False,0
3,ab1644,UAL1962,United States,1747145541.0,1747145541,-84.8758,33.2905,3901.44,False,184.24,47.49,-8.78,NaN,3985.26,0760,False,0
4,e8027c,LPE2458,Chile,1747145535.0,1747145535,-78.1609,-10.412,9486.9,False,222.63,330.06,5.2,NaN,10058.4,NaN,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10666,abc0e4,SWA4765,United States,1747145541.0,1747145541,-118.2883,33.9636,594.36,False,88.57,263.33,-4.55,NaN,586.74,3324,False,0
10667,ad5c72,TG42,United States,1747145531.0,1747145534,-103.8711,38.2245,2072.64,False,49.56,279.56,0.0,NaN,1996.44,NaN,False,0
10668,4caa32,ITY610,Ireland,1747145541.0,1747145541,7.4285,43.6678,11582.4,False,235.28,326.41,-0.33,NaN,11681.46,4027,False,0
10669,a6d83c,DAL367,United States,1747145542.0,1747145542,-116.4416,33.2877,7056.12,False,230.21,23.3,9.75,NaN,7277.1,NaN,False,0
10670,e94c86,BOV736,Bolivia,1747145541.0,1747145541,-55.926,-19.8435,11277.6,False,239.4,113.42,0.0,NaN,11948.16,NaN,False,0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10671 entries, 0 to 10670
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   icao24           10671 non-null  object
 1   callsign         10500 non-null  object
 2   origin_country   10670 non-null  object
 3   time_position    10583 non-null  object
 4   last_contact     10671 non-null  object
 5   longitude        10583 non-null  object
 6   latitude         10583 non-null  object
 7   baro_altitude    9825 non-null   object
 8   on_ground        10671 non-null  object
 9   velocity         10671 non-null  object
 10  true_track       10671 non-null  object
 11  vertical_rate    9863 non-null   object
 12  sensors          0 non-null      object
 13  geo_altitude     9719 non-null   object
 14  squawk           6534 non-null   object
 15  spi              10671 non-null  object
 16  position_source  10671 non-null  object
dtypes: object(17)
memory usage: 1.4+ MB

In [18]:
df["last_contact"] = df["last_contact"].astype(float)
df["time_position"] = df["time_position"].astype(float)
df["latitude"] = df["latitude"].astype(float)
df["longitude"] = df["longitude"].astype(float)
df["baro_altitude"] = df["baro_altitude"].astype(float)
df["velocity"] = df["velocity"].astype(float)
df["true_track"] = df["true_track"].astype(float)
df["vertical_rate"] = df["vertical_rate"].astype(float)
df["geo_altitude"] = df["geo_altitude"].astype(float)
df["position_source"] = df["position_source"].astype(int)
df["on_ground"] = df["on_ground"].astype(bool)
df["spi"] = df["spi"].astype(bool)
df["last_contact"] = pd.to_datetime(df["last_contact"], unit="s", errors="coerce")
df["time_position"] = pd.to_datetime(df["time_position"], unit="s", errors="coerce")
df

,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,sensors,geo_altitude,squawk,spi,position_source
0,39de4e,TVF33SN,France,2025-05-13 14:12:18,2025-05-13 14:12:21,-3.6839,41.0241,10965.18,True,238.40,30.33,0.00,NaN,11049.00,6402,True,0
1,c07d0b,CGVJE,Canada,2025-05-13 14:12:21,2025-05-13 14:12:21,-74.3807,45.6245,297.18,True,48.42,47.15,-2.28,NaN,327.66,NaN,True,0
2,3ffc29,DMFSS,Germany,2025-05-13 14:11:30,2025-05-13 14:11:30,12.8925,48.2168,1219.20,True,42.19,52.43,-0.33,NaN,NaN,4453,True,0
3,ab1644,UAL1962,United States,2025-05-13 14:12:21,2025-05-13 14:12:21,-84.8758,33.2905,3901.44,True,184.24,47.49,-8.78,NaN,3985.26,0760,True,0
4,e8027c,LPE2458,Chile,2025-05-13 14:12:15,2025-05-13 14:12:15,-78.1609,-10.4120,9486.90,True,222.63,330.06,5.20,NaN,10058.40,NaN,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10666,abc0e4,SWA4765,United States,2025-05-13 14:12:21,2025-05-13 14:12:21,-118.2883,33.9636,594.36,True,88.57,263.33,-4.55,NaN,586.74,3324,True,0
10667,ad5c72,TG42,United States,2025-05-13 14:12:11,2025-05-13 14:12:14,-103.8711,38.2245,2072.64,True,49.56,279.56,0.00,NaN,1996.44,NaN,True,0
10668,4caa32,ITY610,Ireland,2025-05-13 14:12:21,2025-05-13 14:12:21,7.4285,43.6678,11582.40,True,235.28,326.41,-0.33,NaN,11681.46,4027,True,0
10669,a6d83c,DAL367,United States,2025-05-13 14:12:22,2025-05-13 14:12:22,-116.4416,33.2877,7056.12,True,230.21,23.30,9.75,NaN,7277.10,NaN,True,0
10670,e94c86,BOV736,Bolivia,2025-05-13 14:12:21,2025-05-13 14:12:21,-55.9260,-19.8435,11277.60,True,239.40,113.42,0.00,NaN,11948.16,NaN,True,0